using CommandLine;
using Piral.Blazor.Cli;
using System.Reflection;

static void ShowBot(string message)
{
    var bot = @$"
    {message}
    __________________
                      \
                       \
                          ....
                          ....'
                           ....
                        ..........
                    .............'..'..
                 ................'..'.....
               .......'..........'..'..'....
              ........'..........'..'..'.....
             .'....'..'..........'..'.......'.
             .'..................'...   ......
             .  ......'.........         .....
             .    _            __        ......
            ..    #            ##        ......
           ....       .                 .......
           ......  .......          ............
            ................  ......................
            ........................'................
           ......................'..'......    .......
        .........................'..'.....       .......
     ........    ..'.............'..'....      ..........
   ..'..'...      ...............'.......      ..........
  ...'......     ...... ..........  ......         .......
 ...........   .......              ........        ......
.......        '...'.'.              '.'.'.'         ....
.......       .....'..               ..'.....
   ..       ..........               ..'........
          ............               ..............
         .............               '..............
        ...........'..              .'.'............
       ...............              .'.'.............
      .............'..               ..'..'...........
      ...............                 .'..............
       .........                        ..............
        .....
";
    Console.WriteLine(bot);
}

static int RunCreateEmulator(CreateEmulatorOptions opts)
{
    return 0;
}

static int RunPrefillCache(PrefillCacheOptions opts)
{
    return 0;
}

static int ShowError(IEnumerable<Error> errs)
{
    if (errs.Where(err => err is not HelpVerbRequestedError && err is not VersionRequestedError).Any())
    {
        ShowBot("That did not work.");
        return 1;
    }

    return 0;
}

Parser.Default.ParseArguments<CreateEmulatorOptions, PrefillCacheOptions>(args)
    .MapResult(
        (CreateEmulatorOptions opts) => RunCreateEmulator(opts),
        (PrefillCacheOptions opts) => RunPrefillCache(opts),
        errs => ShowError(errs)
    );
